### ISSUE TITLE
Usage of EmptyDir volume "dshm" exceeds the limit "512Mi".

### ISSUE THREAD

**Issue by LisaShen0509** [JSHZT/ppmattingv2_pytorch#2]
Hello, thank you for open-sourcing such a powerful model!
I encountered an issue while training PPMattingV2 using a custom dataset (with images of size 512x512) on the OpenPAI cluster.

Partial configuration is as follows:
```
batch_size: 8
iters: 100
```

Code：
```
export CUDA_VISIBLE_DEVICES=0
python tools/train.py \
       --config configs/ppmattingv2/ppmattingv2-stdc1-human_512.yml \
       --do_eval \
       --use_vdl \
       --save_interval 15 \
       --num_workers 5 \
       --save_dir output/ppmattingv2_wifi
```
The model can be successfully initialized, but it encounters an error after the following information is output to the console：
```
/mnt/share/syl/vf_env/lib/python3.7/site-packages/paddle/nn/layer/norm.py:778: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance."
size : [128, 128]
size : [256, 256]
size : [64, 64]
```
Error message：`Usage of EmptyDir volume "dshm" exceeds the limit "512Mi".`
When running other code, this error does not occur. Has anyone else encountered this error?

**Comment by LisaShen0509** [comment]
The same error occurs when training with the PPM-100 dataset, and the specific error message is as follows:
```
[Exit Trigger Info]

ExitTriggerMessage: FailedTaskCount 1 has reached MinFailedTaskCount 1 in the TaskRole
ExitTriggerTaskRole: taskrole
ExitTriggerTaskIndex: 0

--------------------------------------------------------------------------------

[Exit Spec]

code: -1000
phrase: PodEvicted
issuer: PAI_K8S
causer: PAI_K8S
type: PLATFORM_FAILURE
stage: RUNNING
behavior: TRANSIENT
reaction: ALWAYS_RETRY
reason: 'Pod is evicted by K8S, maybe its node is out of resource'
repro:
  - Start a raw process on the host to use up almost all memory on the node
solution:
  - Wait result from next retry
  - Contact Cluster Admin
pattern:
  controllerPodPatterns:
    - reasonRegex: (?i)^Evicted$
      messageRegex: (?ms).*


--------------------------------------------------------------------------------

[Exit Diagnostics]

Pod failed: PodPattern matched:
reason: Evicted
message: 'Usage of EmptyDir volume "dshm" exceeds the limit "512Mi". '
```
